php:
  build: ./.docker/build/php
  volumes:
    - ./:/src
    - ./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
  links:
    - mysql

mysql:
  image: mysql:5.7.28
  volumes:
    - ./.docker/volumes/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123123
    MYSQL_USER: magento
    MYSQL_PASSWORD: magento
    MYSQL_DATABASE: magento
  ports:
    - 3306:3306

nginx:
  image: nginx:1.17.6-alpine
  volumes:
    - ./:/src
    - ./.docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - 80:80
  links:
    - php